# shellcheck shell=bash
# motspilot — help command.
# Sourced by motspilot.sh; not meant to be run on its own.

# ── help ────────────────────────────────────────────────────────────
cmd_help() {
    echo -e "  ${BOLD}Usage:${NC}"
    echo ""
    echo -e "    ${CYAN}./motspilot.sh init${NC}                                First-time setup"
    echo -e "    ${CYAN}./motspilot.sh go --task=<name> \"description\"${NC}      Create task + prepare pipeline"
    echo -e "    ${CYAN}./motspilot.sh go --task=<name>${NC}                    Re-prepare existing task"
    echo -e "    ${CYAN}./motspilot.sh go --task=<name> --from=<phase>${NC}     Prepare to re-run from a phase"
    echo -e "    ${CYAN}./motspilot.sh tasks${NC}                               List active tasks"
    echo -e "    ${CYAN}./motspilot.sh tasks --all${NC}                         List active + archived tasks"
    echo -e "    ${CYAN}./motspilot.sh status [--task=<name>]${NC}              Detailed task status"
    echo -e "    ${CYAN}./motspilot.sh archive --task=<name>${NC}               Archive a completed task"
    echo -e "    ${CYAN}./motspilot.sh reactivate <name>${NC}                   Restore task from archive"
    echo -e "    ${CYAN}./motspilot.sh reset --task=<name>${NC}                 Reset phase artifacts (keeps requirements)"
    echo -e "    ${CYAN}./motspilot.sh view <phase> [--task=<name>]${NC}        View a phase artifact"
    echo -e "    ${CYAN}./motspilot.sh mem-check${NC}                           Check memory index health (line/byte caps, staleness)"
    echo ""
    echo -e "  ${BOLD}Global flag:${NC}  ${CYAN}--project=<path>${NC}  Override project directory detection"
    echo ""
    echo -e "  ${BOLD}Tip:${NC}  Omit ${CYAN}--task=${NC} on any command to get an interactive task picker."
    echo ""
    echo -e "  ${BOLD}Phases:${NC}  architecture · development · testing · verification · delivery"
    echo -e "  ${BOLD}View shortcuts:${NC}  req · arch · dev · test · verify · wo (workorder)"
    echo ""
    echo -e "  ${BOLD}Setup:${NC}"
    echo ""
    echo -e "    ${DIM}# Option A: Symlink the directory${NC}"
    echo -e "    ln -s /path/to/motspilot myproject/motspilot"
    echo -e "    cd myproject && ./motspilot/motspilot.sh init"
    echo ""
    echo -e "    ${DIM}# Option B: Symlink just the script${NC}"
    echo -e "    ln -s /path/to/motspilot/motspilot.sh myproject/motspilot.sh"
    echo -e "    cd myproject && ./motspilot.sh init"
    echo ""
    echo -e "    ${DIM}# Option C: Run directly from project dir${NC}"
    echo -e "    cd myproject && bash /path/to/motspilot/motspilot.sh init"
    echo ""
    echo -e "  ${BOLD}Workflow:${NC}"
    echo ""
    echo -e "    1. ${YELLOW}./motspilot.sh go --task=add-csv \"Add CSV export\"${NC}"
    echo -e "    2. ${YELLOW}Claude Code: run motspilot pipeline${NC}      ← AI orchestrates all phases"
    echo -e "    3. Task auto-archives on completion"
    echo ""
    echo -e "  ${BOLD}Bug fix on completed task:${NC}"
    echo ""
    echo -e "    1. ${YELLOW}./motspilot.sh reactivate add-csv${NC}"
    echo -e "    2. ${YELLOW}./motspilot.sh go --task=add-csv --from=development${NC}"
    echo -e "    3. ${YELLOW}Claude Code: run motspilot pipeline${NC}"
    echo ""
}
